version: '3.8'
services:
  app-category01:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3010:3000
    volumes:
      - .:/app


  pgsql-category01:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    volumes:
      - ./.docker/pgsql/dbdata:/var/lib/postgresql/data
    environment:
      - NODE_ENV=development
      - DB_HOST=pgsql-category01
      - DB_PORT=5432
      - DB_USERNAME=pguser
      - DB_PASSWORD=pgpassword
      - DB_DATABASE=nestjs
  
  # mongodb:
  #   image: mongo:4.4.4
  #   restart: always
  #   volumes:
  #     - ./docker/mongo/dbdata:/data/db
  #     - ./docker/mongo:/docker-entrypoint-initdb.d
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #     - MONGO_INITDB_DATABASE=catalogo


  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8085:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #     - ME_CONFIG_MONGODB_AUTH_USERNAME=root
  #     - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=root
  #   depends_on:
  #     - mongodb

      
  adminer-category01:
    image: adminer
    restart: always
    ports:
      - 8080:8080



networks:
  default:
    external:
      name: category01

