apiVersion: v1
kind: Secret
metadata:
  name: keyautomacao
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImRHOXdkMkY1YzNsemRHVnRjenB5WjJsdVptOGpJelUyTXpkdFlRPT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9
type: kubernetes.io/dockerconfigjson