version: '3.8'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapeia a porta 3000 do container para a porta 3000 do host
    volumes:
      - .:/app # Monta o diretório atual no container
